version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agregator_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Laravel API
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: agregator_db
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - mysql
    command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: agregator_db
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - mysql
    command: php artisan queue:work --sleep=3 --tries=3

  # Scheduler
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: agregator_db
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - mysql
    command: php artisan schedule:work

volumes:
  mysql_data:
